{
  "keyLength": 2048,
  "io": false,
  "webUrl": "https://c.51itou.com/manage",
  "thirdPartUrlPrefix": [
    "https://cash.yeepay.com",
    "https://m.51yueqian.com",
    "https://wap.beeplaying.com",
    "https://h5.jdddata.com/communal/cartoonKou/fulllive",
    "http://cash.yeepay.com",
    "http://m.51yueqian.com",
    "http://wap.beeplaying.com",
    "http://h5.jdddata.com/communal/cartoonKou/fulllive",
    "https://itou.caihongduoduo.com",
    "http://itou.caihongduoduo.com",
    "http://koudai.jindianle.com/others/scheme/index.html",
    "https://koudai.jindianle.com/others/scheme/index.html",
    "https://youdian.jindianle.com/others/scheme/index.html",
    "http://youdian.jindianle.com/others/scheme/index.html",
    "https://update-0001.jindianle.com/hot_code_com.itou.sim.client_dist/koudai",
    "http://update-0001.jindianle.com/hot_code_com.itou.sim.client_dist/koudai",
    "https://update-0001.51itou.com/hot_code_com.itou.sim.client_dist/koudai",
    "http://update-0001.51itou.com/hot_code_com.itou.sim.client_dist/koudai",
    "https://engine.qazxsdc.com/index/activity",
    "http://engine.qazxsdc.com/index/activity",
    "https://activity4.xinxuezl.com/activity",
    "http://activity4.xinxuezl.com/activity"
  ],
  "androidThirdPartUrlPrefix": [
    "https://cash.yeepay.com",
    "https://m.51yueqian.com",
    "https://wap.beeplaying.com",
    "https://h5.jdddata.com/communal/cartoonKou/fulllive",
    "http://cash.yeepay.com",
    "http://m.51yueqian.com",
    "http://wap.beeplaying.com",
    "http://h5.jdddata.com/communal/cartoonKou/fulllive",
    "https://itou.caihongduoduo.com",
    "http://itou.caihongduoduo.com",
    "http://koudai.jindianle.com/others/scheme/index.html",
    "https://koudai.jindianle.com/others/scheme/index.html",
    "https://youdian.jindianle.com/others/scheme/index.html",
    "http://youdian.jindianle.com/others/scheme/index.html",
    "https://update-0001.jindianle.com/hot_code_com.itou.sim.client_dist/koudai",
    "http://update-0001.jindianle.com/hot_code_com.itou.sim.client_dist/koudai",
    "https://update-0001.51itou.com/hot_code_com.itou.sim.client_dist/koudai",
    "http://update-0001.51itou.com/hot_code_com.itou.sim.client_dist/koudai"
  ],
  "schemeLaunchUrl": [
    "weixin://",
    "sms://",
    "tel://",
    "alipays://",
    "mailto:",
    "chsp://"
  ],
  "syncCookiesUrl": "https://c.51itou.com",
  "hotCodeUrl": "https://update-0001.jindianle.com/hot_code_com.wanglizhi.clientd_adhoc/koudai/",
  "hotCodeZipUrl": "https://update-0001.jindianle.com/hot_code_com.wanglizhi.clientd_adhoc/koudai_zip/",
  "enableHotCode": false,
  "enableHotCodeZip": false,
  "enableBlue": true,
  "dsn": "https://bb07f385190d468ab0a268d58d4073fb@o423880.ingest.sentry.io/5354926",
  "reloadDelay": 250
}
